name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install uv and Python
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "latest"
          python-version: "3.12"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --all-packages --all-extras --dev

      - name: Run Ruff Lint Check
        run: uv run ruff check .

      - name: Run Ruff Format Check
        run: uv run ruff format --check .

      - name: MyPy Type-checking
        run: uv run --all-packages mypy .

      - name: Run Test Suite
        run: uv run --all-packages pytest
